language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t codyoakes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codyoakes/docker-react npm run test
