language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t codyoakes/docker-react -f Dockerfile.dev .

script:
  - docker run codyoakes/docker-react npm run test -- --coverage
